language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - pytest --cov=main tests/
after_success:
  - coveralls